export const OFFER_CHECKOUT = 'OFFER_CHECKOUT';
export const OFFER_SET_ACTIVE_SCREEN = 'OFFER_SET_ACTIVE_SCREEN';
export const PERILS_DIALOG_SHOWN = 'PERILS_DIALOG_SHOWN';
export const PERILS_DIALOG_DISMISSED = 'PERILS_DIALOG_DISMISSED';
export const PERILS_SET_ACTIVE = 'PERILS_SET_ACTIVE';
export const PERILS_UNSET_ACTIVE = 'PERILS_UNSET_ACTIVE';
