export const BANKID_SIGN = 'BANKID_SIGN';
export const BANKID_SIGN_CLIENT_FAILED_TO_OPEN =
  'BANKID_SIGN_CLIENT_FAILED_TO_OPEN';
export const BANKID_SIGN_RESPONSE = 'BANKID_SIGN_RESPONSE';
export const BANKID_SIGN_COMPLETE = 'BANKID_SIGN_COMPLETE';
export const BANKID_SIGN_FAILED = 'BANKID_SIGN_FAILED';
export const BANKID_SIGN_CANCEL = 'BANKID_SIGN_CANCEL';
export const BANKID_SIGN_RESET = 'BANKID_SIGN_RESET';
export const BANKID_COLLECT = 'BANKID_COLLECT';
export const BANKID_COLLECT_PREPARE = 'BANKID_COLLECT_PREPARE';
export const BANKID_COLLECT_RESPONSE = 'BANKID_COLLECT_RESPONSE';
export const BANKID_COLLECT_COMPLETE = 'BANKID_COLLECT_COMPLETE';
export const BANKID_COLLECT_FAILED = 'BANKID_COLLECT_FAILED';
export const BANKID_COLLECT_CANCEL = 'BANKID_COLLECT_CANCEL';
export const BANKID_COLLECT_RESET = 'BANKID_COLLECT_RESET';
export const BANKID_DIALOG_SHOWN = 'BANKID_DIALOG_SHOWN';
export const BANKID_DIALOG_DISMISSED = 'BANKID_DIALOG_DISMISSED';
