export const MARKETING_CHAT_START = 'MARKETING_CAROUSEL/CHAT_START';
export const MARKETING_CHAT_LOGIN = 'MARKETING_CAROUSEL/CHAT_LOGIN';
export const MARKETING_SET_ACTIVE_SCREEN = 'MARKETING/SET_ACTIVE_SCREEN';
