source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'hedvig' do
  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge",
      "RCTLinkingIOS"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'Analytics'
  pod 'Segment-Facebook-App-Events'
  # pod 'Segment-Branch'
  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
  pod 'Branch-SDK', :path => '../node_modules/react-native-branch/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNAudio', :path => '../node_modules/react-native-audio'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-config', :path => '../node_modules/@hedviginsurance/react-native-config'
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

end
